version: '3.9'
services:
  db:
    image: postgres:16
    container_name: gestor_db
    environment:
      POSTGRES_DB: sistema_gestor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sistema_gestor"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: gestor_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dv
      SERVER_PORT: 8080
      DATABASE_URL: jdbc:postgresql://db:5432/sistema_gestor
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  dbdata:

